
[input]
;input_folder = C:\Users\steaime\Documents\Research\Codes\Rheoflu\testPIV\test1\
; If empty string, process all images in input folder in consecutive pairs.
; Otherwise, load frame A and frame B by filtering separately
;filter_frameA = exp1_001_a.bmp
;filter_frameB = exp1_001_b.bmp
; Region of interest: (xmin,xmax,ymin,ymax) or 'full' for full image
ROI = full
; 'None' for no masking, 'edges' for edges masking, 'intensity' for intensity masking
; WARNING: This part is under development so better not to use MASKS
masking_method = None

[processing]
; 'circular' or 'linear'
correlation_method = circular
; number of PIV passes
iterations = 6
; interroagtion window size for each pass. It should be a power of 2 
window_sizes = [128, 64, 32, 16, 8, 4]
; overlap of the interroagtion window for each pass.
; Has to be a value with base two. In general window size/2 is a good choice.
overlap = [64, 32, 16, 8, 4, 2]
; Method used for subpixel interpolation: 'gaussian','centroid','parabolic'
subpixel_method = parabolic
; order of the image interpolation for the window deformation
interpolation_order = 3
; scaling factor pixel/meter
pixel_size = 1.0
; time between to frames (in seconds)
dt = 1.0
; It is possible to decide if the S/N should be computed (for the last pass) or not
extract_sig2noise = false
; method used to calculate the signal to noise ratio 'peak2peak' or 'peak2mean'
sig2noise_method = peak2peak
; select the width of the masked to masked out pixels next to the main peak
sig2noise_mask = 2

[validation]
; choose if you want to do validation of the first pass: True or False
; only effecting the first pass of the interrogation: the following passes
; in the multipass will be validated
validation_first_pass = false
; The validation is done at each iteration based on three filters.
; The first filter is based on the min/max ranges. 
; Note that these values are defined in terms of minimum and maximum displacement in pixel/frames.
MinMax_U_disp = [-20, 20]
MinMax_V_disp = [-20, 20]
; The second filter is based on the global STD threshold
std_threshold = 7
; The third filter is the median test (not normalized at the moment)
median_threshold = 3
median_size = 1
; On the last iteration, an additional validation can be done based on the S/N.
; Note: only available when extract_sig2noise==True and only for the last
; pass of the interrogation. Enable the signal to noise ratio validation. Options: True or False
do_sig2noise_validation = false
; minmum signal to noise ratio that is need for a valid vector
sig2noise_threshold = 1.2
; Replacment options for vectors which are masked as invalid by the validation
replace_vectors = true
; Enables smoothing of the displacemenet field
smoothn = true
; smoothing parameter
smoothn_p = 0.5 
; select a method to replace the outliers: 'localmean', 'disk', 'distance'
filter_method = localmean
; maximum iterations performed to replace the outliers
max_filter_iteration = 4
; kernel size for the localmean method
filter_kernel_size = 2

[output]
;output_folder = C:\Users\steaime\Documents\Research\Codes\Rheoflu\testPIV\test1\out
;save_folder_suffix = test

; Select if you want to save the plotted vectorfield: True or False
save_plot = true
; Choose whether you want to see the vectorfield or not :True or False
show_plot = true
; select a value to scale the quiver plot of the vectorfield
scale_plot = 200